### ISSUE TITLE
The site has been inaccessible

### ISSUE THREAD

**Issue by Z8264** [bestofjs/bestofjs#156]
![image](https://user-images.githubusercontent.com/7948534/187676880-1573d843-9e86-4cae-8170-086d4a641189.png)

**Comment by michaelrambeau** [comment]
Hello @Z8264 
Can you confirm that the problem persisted after reloading the window?
I'm asking because you can see this message when you keep your browser open, make the computer enter in sleep mode and go back, because it can take a few seconds to restore the connection.

**Comment by Z8264** [comment]
![image](https://user-images.githubusercontent.com/7948534/187827935-58736c03-741a-4665-9de8-d7bc5f7b71ec.png)
Not sure why this interface cannot be accessed.

**Comment by Z8264** [comment]
This may be caused by the inability to access a specific interface due to policy restrictions.

**Comment by michaelrambeau** [comment]
Thank you for the report, it seems the site has been blocked in China 😢 .
The strange thing is that you can access the page (on `bestofjs.org` domain), it's only the API call to `bestofjs-static-api.vercel.app` domain that fails, if my understanding is correct, can you confirm?

**Comment by Z8264** [comment]
Your judgment is correct. I am in China. I can access the page, but no data.

**Comment by L1lith** [comment]
@michaelrambeau might we be able to mitigate this issue by solving [this issue](https://github.com/bestofjs/bestofjs-webui/issues/114)?

**Comment by kenkozheng** [comment]
@michaelrambeau  It seems to be an issue of HTTPS certification.
![image](https://user-images.githubusercontent.com/6870512/199872435-cfbc0747-695d-487b-a6c3-30fec0848ecc.png)
![image](https://user-images.githubusercontent.com/6870512/199872508-bc0ee2c6-0416-4f18-a55d-01c666574bfc.png)

**Comment by michaelrambeau** [comment]
Thank you @kenkozheng for the investigation, that certification error is weird.

What I can do is prepare a new version of the application that does not fetch data from an external domain since it seems your browser cannot make requests to `vercel.app` domain.

I will contact you as soon as I have a new version to check.

**Comment by JakeVivit** [comment]
@michaelrambeau Is there a solution? I am in China and have been unable to access the website for a long time

**Comment by michaelrambeau** [comment]
Hello @JakeVivit sorry for the pain 🥲 

I'm working on a new architecture based on Next.js that could solve some of the issues related to CORS requests.

It's only a prototype (temporary URL, please don't share) but you could check if this link works for you: https://bestofjs-try-next13.vercel.app/ ?

**Comment by JakeVivit** [comment]
> Hello @JakeVivit sorry for the pain 🥲
> 
> I'm working on a new architecture based on Next.js that could solve some of the issues related to CORS requests.
> 
> It's only a prototype (temporary URL, please don't share) but you could check if this link works for you: https://bestofjs-try-next13.vercel.app/ ?

This link is not useful to me, thank you very much for replying！！！

**Comment by michaelrambeau** [comment]
@Z8264  Could you give me more details and explain how the prototype I shared behaves for you, what page work and what waht do not work?

**Comment by michaelrambeau** [comment]
Closing for now but let me know how the latest beta version works: https://beta.bestofjs.org/

I hope it could solve issues related to CORS requests from the browser.
