### ISSUE TITLE
为啥访问不了呢

### ISSUE THREAD

**Issue by 17770137331** [bestofjs/bestofjs#167]
![b623734021122e2af62dda42f0661fd](https://user-images.githubusercontent.com/56908297/227399078-2b41a377-94cc-4a87-92a2-6b365e879c8c.png)

**Comment by michaelrambeau** [comment]
Hello @17770137331 thank you for the report!

I'm afraid it's the same problem as https://github.com/bestofjs/bestofjs-webui/issues/156, currently data is provided by a request made to a domain that is not available from your location.

I will try to address this issue and contact you to check.

**Comment by michaelrambeau** [comment]
Hello @17770137331 I'm preparing a new version of _Best of JS_, built on top of Next.js

Could you check if this URL works from your location: https://beta.bestofjs.org/ ?

**Comment by michaelrambeau** [comment]
Closing but let me know how the beta version works, I hope it could solve issue related to CORS requests.
