### ISSUE TITLE
Aggregated chart data for 09/2023 are missing

### ISSUE THREAD

**Issue by panva** [bestofjs/bestofjs#209]
The september columns are not available

![image](https://github.com/bestofjs/bestofjs/assets/241506/8c9d84a5-041e-4e6a-9f24-5e1f75b426fa)

**Comment by michaelrambeau** [comment]
Hello Fillip @panva thank you, I have noticed that problem too, it's related to how data is cached by the new Next.js app.

I have reset data, could you check again?

**Comment by panva** [comment]
Yup, it's present now.

**Comment by panva** [comment]
Actually, stars are visible but npm downloads are not.

**Comment by michaelrambeau** [comment]
Sorry @panva for the miss, I had to reset package download data too.

Could you check again?

Thank you again for your patience!

For the records, what we do here, to invalidate the cache every 24 hours, does not work.

https://github.com/bestofjs/bestofjs/blob/486025a2a16a4f51763c915efc3f5d5ab0e5fe2a/apps/bestofjs-nextjs/src/app/projects/%5Bslug%5D/project-details-npm/monthly-downloads-charts.tsx#L29-L39

**Comment by zawarudo** [comment]
At least on [https://bestofjs.org/projects/shadcnui](https://bestofjs.org/projects/shadcnui)

Stars and downloads are working for me.

![image](https://github.com/bestofjs/bestofjs/assets/2955134/e1513528-2d2a-454b-a668-0cd499d088d9)
![image](https://github.com/bestofjs/bestofjs/assets/2955134/e8ec8955-6495-463a-b791-335a46465bb6)

**Comment by panva** [comment]
It is all visible now indeed.
