### ISSUE TITLE
Add "hover cards" to get a quick overview of projects and tags

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs#217]
## The need

I noticed a nice pattern in GitHub: when a repository, a commit or a user is mentioned, by hovering the link it's possible to get an overview about the link in a popup window.

Examples:

#### Repository link from the default feed

![image](https://github.com/bestofjs/bestofjs/assets/5546996/a8a8d6e3-82e9-491d-be01-820bcb4c60ae)

#### GitHub avatar and username from an issue

![image](https://github.com/bestofjs/bestofjs/assets/5546996/e8fccdbe-e6e7-46c0-b426-0dca71ec4485)

#### Link to PR from PR list

![image](https://github.com/bestofjs/bestofjs/assets/5546996/e5bb7303-e4ef-4b22-84d9-4066a91f0a3a)

#### Commit link from a comment

![image](https://github.com/bestofjs/bestofjs/assets/5546996/985bb46b-7406-41fd-a3c8-95299b3b23e4)

#### In Discord

I have seen a similar pattern in some Discord servers (the Next.js one for example): you get an overview of the content of a channel when you hover a channel name, from the left sidebar:

![image](https://github.com/bestofjs/bestofjs/assets/5546996/6ab9c9b4-e1bd-45f1-ad0a-ed1c9c943ec3)

I'd like to see the same feature in _Best of JS_, especially for projects and for tags, as the definition and the scope of tags is not often obvious.

It should be easy to implement as `shadcn/ui` components include "hover cards": https://ui.shadcn.com/docs/components/hover-card

## What to show

When hovering a tag link, I'd like to see:

- the tag description
- a list of the 5 most popular projects included
- a link to the tag page

**Comment by michaelrambeau** [comment]
At first, I think the cards would be useful for the tag links we have inside each project row, in every project list, because the meaning of the tags is not not always obvious.

The card would show:

- a summary of the other projects available under the tag
- a description of the tag (I need to make the tags description available in the API)

**Comment by Evomatic** [comment]
That is understandable. For now I will focus on making it viable for each project row on the `/projects` page. 

Here is a demo of it in action!

https://github.com/bestofjs/bestofjs/assets/27636896/8540efa6-4dd8-4da0-9042-84094226c848

**Comment by Evomatic** [comment]
@michaelrambeau I added a hover card component for the `/projects` page but having some difficulty finding the best way to retrieve the projects associated with the tag. With the current implementation the tag parameter passed [here](https://github.com/bestofjs/bestofjs/pull/257/files#diff-80c1905d819e3b8bf07f40379b299829f2f5ce22c919faaca8f4d989614eb5b9R78) (from my PR) passes tag with the `description` data I need but no associated project data. I think I need the version of the tag data that is passed for `TagWithProjects` type as seen in `/tags` [here](https://github.com/bestofjs/bestofjs/blob/6a308e75cd8be7804a780e67ae305d182bae1249/apps/bestofjs-nextjs/src/components/tag-list/tag-list.tsx#L16C29-L16C29). Any recommendations?

Also:

> The card would show:
    a summary of the other projects available under the tag
    a description of the tag (I need to make the tags description available in the API)
    
    How should the layout for the content look? Something like the list of projects then the description? Maybe similar to OG images? 🤔

**Comment by michaelrambeau** [comment]
The layout of the card could be:

- Tag icon followed by the tag name
- Tag description
- "TOP 5 projects" followed by a list of projects icon and name

About the implementation, the problem is how to grab the TOP 5 projects for each tag.
I can see 2 options:

- server side pattern: make the `api.projects.findProjects()` return projects with tags that include information about the projects. Inconvenient: if you already ask for the the projects related to a given tag (E.g. `/projects?tags=react`), all projects would include the same tag that would in turn include the same projects, it can work but it's just a lot of duplicate data we send over the wire.
- client-side approach: we already have the tag name and description, what is missing is the TOP 5, we could load them by calling a new API end-point `/api/tags/[slug]` that returns all data about a given tag. That means the cards would show up initially with the tag name, description and a "skeleton" showing 5 lines, before showing actual data.

**Comment by michaelrambeau** [comment]
Fixed by #257
