### ISSUE TITLE
Question about the monthly stars data

### ISSUE THREAD

**Issue by jkzing** [bestofjs/bestofjs#262]
I found that the monthly stars data seems to be not very accurate.

For example, the data of the Rspack project is like this:

![CleanShot 2024-01-05 at 16 43 02@2x](https://github.com/bestofjs/bestofjs/assets/2851517/9efdbc24-08f2-4756-8d16-5c74e74c4877)

The summary of the stars increasing in 2023 is about 3.5k.

But the star growth trend I saw from star-history.com (https://star-history.com/#web-infra-dev/rspack) is like this:

![CleanShot 2024-01-05 at 16 45 51@2x](https://github.com/bestofjs/bestofjs/assets/2851517/2558cbe6-78ef-4eea-93c9-39d00a7d0dee)

Obviously, the growth number of Rspack in 2023 is beyond 3.5k stars.

I try to write a script to do the samething like star-history.com:

```js
const months = [];
const collectData = async (page) => {
  const data = await fetch(
    `https://api.github.com/repos/web-infra-dev/rspack/stargazers?per_page=30&page=${page}`,
    {
      headers: {
        Authorization: '*** github token ***',
        Accept: 'application/vnd.github.v3.star+json',
      },
    },
  ).then((r) => r.json());
  for (const item of data) {
    const date = new Date(item.starred_at);
    if (date.getFullYear() === 2023) {
      // only collect data for year 2023
      const m = date.getMonth();
      if (!months[m]) {
        months[m] = 1;
      }
      months[m] += 1;
    }
  }
  return Boolean(data.length);
};
let page = 1;
while (await collectData(page)) {
  page++;
}
console.log(months);
```

It gives me this result:

```js
[4, 5, 3681, 505, 285, 360,  238, 245, 131, 359,  436, 263]
```

I am wondering maybe there are some issues during the stars data collection.

**Comment by michaelrambeau** [comment]
@jkzing Thank you for your patience and sorry for the miss!

Missing data has been added, it moves Rspack at the position 5!

![image](https://github.com/bestofjs/bestofjs/assets/5546996/9623843c-cbfb-49a4-9660-13a4ac62ab6b)

**Comment by jkzing** [comment]
@michaelrambeau Awesome and appreciate for your quick response. 🗡️ 

I'm closing this issue now.
