### ISSUE TITLE
Typewriter effect on top page

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs#267]
To make _Best of JS_ page fun and show the variety of domains we cover, I'd like to see a typewrite effect applied on main heading ("The best of JS, HTML, CSS" currently)

The cycle could be:

- Show: `the best of JavaScript`
- Several backspace keystroke to remove the word JavaScript
- keystrokes to add the word `TypeScript`
- remove the word TypeScript
- Add `React`
- And so on with some popular topics like `Vue.js`, `Astro`, `Bun`, `Deno`, `CSS-in-JS`...

Example of projects we could use: https://bestofjs.org/projects/typeit

**Comment by michaelrambeau** [comment]
About the implementation, we should check what Drizzle uses in their top page, because it's exactly the kind of effect I want!

https://orm.drizzle.team/

![Image](https://github.com/bestofjs/bestofjs/assets/5546996/5b1f2632-59dc-4e83-889a-09d53303eb00)

**Comment by Evomatic** [comment]
@michaelrambeau I am interested in taking a look into this unless you wanted to 😄
