### ISSUE TITLE
Embla Carousel - Add tags to project

### ISSUE THREAD

**Issue by davidjerleke** [bestofjs/bestofjs#271]
Hi @michaelrambeau,

Long time no see 🙂. I hope you're all well. I would like to add the following tags to **Embla Carousel** so they show up on the Best of JS website (because Embla now has wrappers for both of these):

- `Solid`
- `Angular`

Alternatively, I can create a PR but in order to do that, I would appreciate if you could point me to a merged PR where the author added new tags to a project.

Thanks in advance!

All the best,
David

**Comment by michaelrambeau** [comment]
Hello David @davidjerleke ! Nice to see you again :)

I'm impressed by the fact that Embla was picked by shadcn/ui components... it says a lot about the quality of your project, congratulations! 🎉 

About _Best of JS_, the management of the projects and their tags is not part of any PR process or workflow, it's done manually, it's something I'd like to improve in the future.

The change you requested will be "live" in a few hours, I will ping you again, stay tuned!

**Comment by michaelrambeau** [comment]
Done, please check @davidjerleke 

https://bestofjs.org/projects/embla-carousel

![image](https://github.com/bestofjs/bestofjs/assets/5546996/1ac03938-21e7-4d0d-b1d7-99db15a640d7)

**Comment by davidjerleke** [comment]
@michaelrambeau legend. Confirmed. Thanks for the help 🎉!
