### ISSUE TITLE
Project tracking proposal: MUI X

### ISSUE THREAD

**Issue by oliviertassinari** [bestofjs/bestofjs#272]
I would propose bestofjs tracks MUI X: https://github.com/mui/mui-x (it builds data grid, charts, date picker, independently from Material UI)

The project received about 300 stars in February https://star-history.com/#mui/mui-x&Date, it could make sense. cc @joserodolfofreitas

---

Regarding https://bestofjs.org/projects/mui, this should really be tracked as Material UI, MUI is an organization but it's a different story: #276

**Comment by michaelrambeau** [comment]
I'm very sorry for the delay Olivier @oliviertassinari  I missed this issue, my bad.

Thank you for the suggestion, MUI X will be available on _Best of JS_ very soon.

**Comment by michaelrambeau** [comment]
Thank you for your patience Olivier @oliviertassinari 

MUI X is available on _Best of JS_, please check: https://bestofjs.org/projects/mui-x
