### ISSUE TITLE
Rename MUI to Material UI

### ISSUE THREAD

**Issue by oliviertassinari** [bestofjs/bestofjs#276]
This is a follow-up on https://github.com/bestofjs/bestofjs/pull/126#issuecomment-1030942781

> Michael Rambeau: it used to be called Material UI but I changed to "MUI" in December when I noticed the description in the official home page was:

For the last 12 months+ we worked toward having only Material UI for the name of the open-source project. We limited the use of MUI to the name of the organization working on this. 

<img width="1045" alt="SCR-20240323-bqzn" src="https://github.com/bestofjs/bestofjs/assets/3165635/00a7eb25-cbbd-4dc6-95f1-e9ad83b53d7c">

https://bestofjs.org/projects/mui

Could we:

- Change "MUI" to "Material UI"
- Change the URL to https://mui.com/material-ui/. Linking to https://mui.com/core/ is OK, but we moved Base UI into its own repository, out of the Material UI repository, and plan to do the same with Pigment CSS.
- Change the URL slug from /projects/mui to /projects/material-ui

Thanks

(cc @danilo-leal for context)

**Comment by michaelrambeau** [comment]
Hello Olivier! @oliviertassinari 
Thank you so much for your interest in _Best of JS_, that means a lot to me 😄 

The project has just been renamed, please check https://bestofjs.org/projects/material-ui

Is it OK to update the project name in the _JS Rising Stars_ project too? (I will update the URLs, at least, to avoid 404 errors)

![image](https://github.com/bestofjs/bestofjs/assets/5546996/f7d1f83c-fcf7-4a07-bae6-439cbab3e289)

**Comment by oliviertassinari** [comment]
> Is it OK to update the project name in the JS Rising Stars project too? (I will update the URLs, at least, to avoid 404 errors)

Oh yes; please, amazing, thanks!

**Comment by michaelrambeau** [comment]
OK Olivier, MUI has been renamed in the Rising Stars projects:

https://risingstars.js.org/2023/en#section-react

![image](https://github.com/bestofjs/bestofjs/assets/5546996/38c5b8a8-a56b-4bd2-bec9-9aaaf0c5ca1f)

There is no `301` redirect feature for project details URL (`/projects/:slug`) but that could be an interesting feature for projects with a long history, like Material UI 😄

**Comment by oliviertassinari** [comment]
@michaelrambeau Appreciated ✨
