### ISSUE TITLE
The homepage suddenly cannot display content

### ISSUE THREAD

**Issue by u3u** [bestofjs/bestofjs#282]
<img width="1512" alt="image" src="https://github.com/bestofjs/bestofjs/assets/20062482/2836de2a-0db2-450f-9aaf-f8ba6bc11c3e">

**Comment by michaelrambeau** [comment]
Hello @u3u thank you for the report, I have never noticed such a bug, can you confirm it still happens and provide more context? Thank you for your help!

**Comment by u3u** [comment]
@michaelrambeau The next day has already recovered, I forgot to check the network request at that time, it was also the first time I saw this error in many years.
