### ISSUE TITLE
Let's be more social!

### ISSUE THREAD

**Issue by michaelrambeau** [bestofjs/bestofjs#64]
I had an interesting discussion with Angelo about what we could do to make _Best of Javascript_ 
more popular among developers from China.

He suggested we could add a feature to share the application on social networks.

> Do you know WeChat from Tencent? Currently it's very popular in China, it's not only a social tool, we use it to share some documents or articles. These 2 icons are Wechat and Friend Loop in Wechat, we could share to specific friend or group or you all friends area. Most of China Apps contain them to make their Apps could be shared easily.
> Most of China Apps contain them to make their Apps could be shared easily.

![image](https://user-images.githubusercontent.com/5546996/44516851-1ab9f300-a701-11e8-85a5-b73329863e1a.png)

> I think we could share Homepage at the 1st step, we should let people know the App at first, and then we also could add to every project to make more details.
But to be honest, we should add more Original Content like Weekly Report, since our customers are Developers, most of them knows Github and knows how to find the project they are interest, `Best of Js` is a great collection app but it doesn't essential  for them, they could find substitute, so we should not only attract them but also keep them, of course it's a long story.

>  First, we should research something about Wechat such as add icon to let people could share. In Wechat, it also has an App names "WeChat Official Account", you could use it to push your weekly report to anybody who like this "WeChat Official Account". I think we could add this as 2nd step.

**Comment by jsun969** [comment]
Kinda interesting xD. Though this issue created in 2018. Wechat (or "WeChat Official Account") is still popular in China. Many Chinese dev learn new things there. (and because of GFW, more and more Chinese even don't know what "GitHub" is!!)

I can do some help for make _best of js_ more popular in China lol

**Comment by michaelrambeau** [comment]
@jsun969 Thank you for the comments

Closing the issue but feel free to suggest any change that could be helpful, thank you!
